In [4]:
import pandas as pd
import numpy as np
data=pd.read_csv("Housing_price_data_set.csv")
data.tail()
size=data['lotsize'].count()

In [6]:
data['num_driveway']=data.driveway.map({'yes':1,'no':0})
data['num_recroom']=data.recroom.map({'yes':1,'no':0})
data['num_fullbase']=data.fullbase.map({'yes':1,'no':0})
data['num_gashw']=data.gashw.map({'yes':1,'no':0})
data['num_airco']=data.airco.map({'yes':1,'no':0})
data['num_prefarea']=data.prefarea.map({'yes':1,'no':0})
X=data[['lotsize','bedrooms','bathrms','stories','num_driveway','num_recroom','num_fullbase','num_gashw','num_airco','garagepl','num_prefarea']].values
Y=data[['price']].values
print(X)

[[5850    3    1 ...    0    1    0]
 [4000    2    1 ...    0    0    0]
 [3060    3    1 ...    0    0    0]
 ...
 [6000    3    2 ...    1    1    0]
 [6000    3    2 ...    1    1    0]
 [6000    3    1 ...    1    1    0]]


In [13]:
one=np.ones(size,dtype=int)
matx=np.insert(X,0,one,axis=1)
transpose_x=np.transpose(matx)
temp=np.matmul(transpose_x,matx)
temp2=np.matmul(transpose_x,maty)
invtemp=np.linalg.inv(temp)
parameters=np.matmul(invtemp,temp2)
print(parameters)

[[-4.03835043e+03]
 [ 3.54630297e+00]
 [ 1.83200347e+03]
 [ 1.43355585e+04]
 [ 6.55694571e+03]
 [ 6.68777889e+03]
 [ 4.51128383e+03]
 [ 5.45238554e+03]
 [ 1.28314063e+04]
 [ 1.26328904e+04]
 [ 4.24482900e+03]
 [ 9.36951324e+03]]
