In [1]:
import numpy as np
import imageio
import matplotlib.pyplot as plt
imagelist=['amy1.png','amy2.png','andrew1.png','andrew2.png','andy1.png','andy2.png','erin1.png','erin2.png','gabe1.png','gabe2.png','hill2.png','hill4.png','jack1.png','jack2.png','zach1.png','zach2.png']

train_img=[]
for file in imagelist:
    first=np.array(imageio.imread('Train/'+file))
    m,n=first.shape
    first=np.reshape(first,(m*n,1))
    train_img.append(first)

print(m,n)
img_train=np.matrix(np.array(train_img))
train_img=np.transpose(img_train)
print(train_img)
m,n=train_img.shape
print("train_img.shape=",m,n)

##calculating average face vector
avgface=np.ones((m,1))
for i in range(0,m):
    avgface[i]=np.mean(train_img[i])
print("The average face vector is",avgface)

##subtracting average face vector from all faces
for i in range(0,n):
    img_train[i]=img_train[i]-np.transpose(avgface)
print("img_train.shape=",img_train.shape)

150 125
[[ 13  28  53 ... 220 163 197]
 [ 20  34  67 ... 217 160 188]
 [ 27  39  53 ... 224 149 193]
 ...
 [174 107   6 ... 197 106  69]
 [126 220   5 ... 237 123  72]
 [128 254   6 ... 252 123  75]]
train_img.shape= 18750 16
The average face vector is [[136.5625]
 [141.625 ]
 [148.375 ]
 ...
 [ 90.0625]
 [ 94.1875]
 [ 98.8125]]
img_train.shape= (16, 18750)


In [2]:
##calculating covariance matrix
covmat=(img_train*np.transpose(img_train))
print("The covariance matrix is")
#print(covmat)

##calculating eigen values out of covariance matrix
eigen,u=np.linalg.eig(covmat)
print("U matrix is")
#print(v)
print("eigen values are")
print(eigen)

a,s,v=np.linalg.svd(covmat)

##determining value of k i.e.(no. of principal components)
summation=np.sum(s)
print(summation)
for k in range(1,len(s)):
    sigma=0
    for i in range(0,k):
        sigma+=s[i]
    sigma=sigma/summation
    if(sigma>=0.95):
        print("selected value of k is",k)
        break

##selecting k eigen vectors from the set of 16 vectors
eigenvectors=np.empty((k,16))
for i in range(0,k):
    temp=np.empty((1,16))
    for j in range(0,16):
        temp[0,j]=u[i,j]
    eigenvectors[i]=temp

#print("selected eigen vectors are",eigenvectors)

##mapping selected eigen vectors to original image size in training set
mappedeigenvectors=train_img*np.transpose(eigenvectors)
print(mappedeigenvectors.shape)

weightmatrix=np.transpose(mappedeigenvectors)*np.transpose(img_train)
print(weightmatrix.shape)

The covariance matrix is
U matrix is
eigen values are
[1995.62534091  526.36200377 -542.47656392  373.80570775  347.28470427
 -417.50588552  201.4544505  -331.93452424  151.97472555  113.09965382
 -239.98114411 -231.20841688 -152.34066293 -122.26041606  -61.63484033
    2.73586741]
5811.684907963562
selected value of k is 13
(18750, 13)
(13, 16)


In [7]:
###Testing unknown face
image=imageio.imread('Test/gabe3.png')
m,n=image.shape
image=np.reshape(image,(m*n,1))
normalisedface=image-avgface
#print(normalisedface.shape)

testweight=np.transpose(mappedeigenvectors)*normalisedface
#print(testweight.shape)
transposeweightmatrix=np.transpose(weightmatrix)
m,n=transposeweightmatrix.shape
flag=0
store=[]
for i in range(0,m):
    difference=transposeweightmatrix[i]-np.transpose(testweight)
    totaldiff=np.sum(np.power(difference,2))
    totaldiff=np.sqrt(totaldiff)
    print(totaldiff)
    store.append(totaldiff)
a=min(store)

print("Minimum Distance = ",a)

1034846197.1692574
1049734703.4585977
1114152431.979243
1098714420.737404
1001741130.8851489
989622349.4768381
1043852228.78924
1039275674.8880974
986572867.3525797
1055901124.010789
1125874939.427601
1137277241.9784276
1055543146.9498239
1025398164.5820712
1133862352.0183012
1115835299.417882
Minimum Distance =  986572867.3525797
